accounts/urls.py
from django.urls import path
from .views import user_login, user_logout, user_register


app_name = "accounts"

urlpatterns = [
    path("login/", user_login, name="login"),
    path("logout/", user_logout, name="logout"),
    path("register/", user_register, name="register"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("project.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from .views import home_page, detail_page, delete_food


urlpatterns = [
    path("", home_page, name="home"),
    path("food/<int:pk>/", detail_page, name="food_detail"),
    path("food/<int:pk>/delete/", delete_food, name="food_delete"),
]

accounts/models.py
from django.db import models

# Create your models here.

project/models.py
from django.db import models


class FoodType(models.Model):
    name = models.CharField(max_length=100, verbose_name="Food Type")

    class Meta:
        verbose_name = "Food Type"
        verbose_name_plural = "Food Types"

    def __str__(self):
        return self.name


class Food(models.Model):
    food_type = models.ForeignKey(FoodType, on_delete=models.CASCADE, verbose_name="Turi")
    name = models.CharField(max_length=100, verbose_name="Nomi")
    ingredients = models.TextField(verbose_name="Tarkibi")
    price = models.IntegerField(verbose_name="Narxi")
    views_count = models.IntegerField(default=0, verbose_name="Ko'rishlar soni")
    image = models.ImageField(upload_to="foods/", verbose_name="Rasmi", null=True, blank=True)

    class Meta:
        verbose_name = "Food"
        verbose_name_plural = "Foods"

    def __str__(self):
        return self.name

accounts/forms.py
from typing import Any
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class UserRegisterForm(UserCreationForm):

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "password1", "password2"]


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

project/forms.py
from typing import Any, Mapping
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList
from .models import Food, FoodType
from django import forms


class FoodForm(forms.ModelForm):

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

    class Meta:
        model = Food
        exclude = ['views_count']


class FoodTypeForm(forms.ModelForm):

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

    class Meta:
        model = FoodType
        fields = "__all__"

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.core.handlers.wsgi import WSGIRequest

from .forms import UserRegisterForm, UserLoginForm


def user_register(request: WSGIRequest):

    if request.method == "POST":
        form = UserRegisterForm(request.POST)

        if form.is_valid():
            user = form.save()

            login(request, user)

            return redirect("home")
    else:
        form = UserRegisterForm()

    context = {"form": form}

    return render(request, "accounts/register.html", context)


def user_login(request: WSGIRequest):
    next = request.GET.get("next")

    if request.method == "POST":
        form = UserLoginForm(data=request.POST)

        if form.is_valid():
            login(request=request, user=form.get_user())

            return redirect(next or "home")

    else:
        form = UserLoginForm()

    context = {"form": form}

    return render(request, "accounts/login.html", context)


def user_logout(request: WSGIRequest):

    logout(request)

    return redirect("accounts:login")

project/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import permission_required, login_required
from django.core.handlers.wsgi import WSGIRequest

from project.models import Food
from .forms import FoodForm


def home_page(request: WSGIRequest):

    user = request.user

    if request.method == "POST" and user.has_perm("project.add_food"):
        form = FoodForm(data=request.POST, files=request.FILES)

        if form.is_valid():
            form.save()

    else:
        form = FoodForm()

    foods = Food.objects.all()

    context = {"foods": foods, "form": form}

    return render(request, "home.html", context)


@login_required(login_url="accounts:login")
def detail_page(request, pk: int):
    food = get_object_or_404(Food, pk=pk)
    foods = Food.objects.exclude(pk=food.pk)

    if request.method == "POST":
        form = FoodForm(instance=food, data=request.POST, files=request.FILES)

        if form.is_valid():
            form.save()

    else:
        form = FoodForm(instance=food)

    food.views_count += 1
    food.save()

    context = {"food": food, "foods": foods, "form": form}

    return render(request, "detail.html", context)


@login_required(login_url="login")
@permission_required(["project.delete_food"], login_url="login")
def delete_food(request, pk: int):

    food = get_object_or_404(Food, pk=pk)

    food.delete()

    return redirect("home")

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}


<div class="container">
    <h2>Kirish</h2>
    <form method="POST" class="w-50 mb-3">
        {% csrf_token %}

        <p>
            <label for="id_username">Username</label>
            <input class="form-control" type="text" id="id_username" name="username" placeholder="johndoe">
        </p>

        <p>
            <label for="id_password">Password</label>
            <input class="form-control" type="password" name="password" id="id_password" placeholder="• • • • • •">
        </p>

        <button type="submit" class="btn btn-primary w-100">Kirish</button>
    </form>

    <a href="{% url 'accounts:register' %}" class="">Ro'yhatdan o'tish</a>

</div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h2>Ro'yxatdan o'tish</h2>

    <form method="POST" class="w-50 mb-3" enctype="multipart/form-data">

        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit" class="btn btn-primary w-100">Ro'yxatdan o'tish</button>
    </form>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/8.0.0/mdb.min.css" rel="stylesheet" />
</head>

<body>

    <nav class="navbar navbar-light bg-body-tertiary">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">Street Food</a>

            <div class="d-flex gap-2 align-items-center">
                {% block action %}

                {% endblock %}


                {% if request.user.is_authenticated %}
                <div class="dropdown">
                    <div class="fw-bold dropdown-toggle p-2 user-select-none" style="cursor: pointer;" data-mdb-dropdown-init>{{ request.user.username }}</div>

                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item bg-danger text-light" href="{% url 'accounts:logout' %}">Logout</a></li>
                    </ul>
                </div>
                {% else %}

                <a href="{% url 'accounts:login' %}" class="btn btn-link">Login</a>
                <a href="{% url 'accounts:register' %}" class="btn btn-primary">Sign up</a>

                {% endif %}
            </div>
        </div>
    </nav>

    <div class="content my-4">
        {% block content %}
        {% endblock content %}
    </div>


    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/8.0.0/mdb.umd.min.js"></script>
</body>

</html>

templates/detail.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
    <div class="row g-4">
        <div class="col-5">
            <div class="card card-body border">
                <img src="{{ food.image.url }}" alt="" style="height: 450px; object-fit: cover;" class="mb-3 border rounded">

                <div class="d-flex align-items-center justify-content-between mb-2">
                    <h3 class="mb-0">{{ food.name }}</h3>
                    <div class="fw-bold">{{ food.price }} so'm</div>
                </div>

                <div class="d-flex align-items-center justify-content-between">
                    <div class="fw-bold">Mahsulot turi</div>
                    <div class="">{{ food.food_type.name }}</div>
                </div>

                <div class="d-flex align-items-center justify-content-between">
                    <div class="fw-bold">Masalliqlar</div>
                    <div class="">{{ food.ingredients }}</div>
                </div>

                <div class="d-flex align-items-center justify-content-between mb-2">
                    <div class="fw-bold">Ko'rishlar soni</div>
                    <div class=""><i class="fas fa-eye"></i> {{ food.views_count }}</div>
                </div>

                <div class="d-flex gap-2 mb-2">

                    {% if perms.project.change_food %}
                    <div class="flex-grow-1 btn btn-warning py-2" data-mdb-ripple-init data-mdb-modal-init data-mdb-target="#edit-food-modal">Yangilash</div>
                    {% endif %}

                    {% if perms.project.delete_food %}
                    <a href="{% url 'food_delete' food.pk %}" class="flex-grow-1 btn btn-danger py-2" onclick="return confirm('{{ food.name }} ni o\'chirish')">O'chirish</a>
                    {% endif %}
                </div>

                <div class="flex-grow-1 btn btn-success py-2">Buyurtma berish</div>
            </div>
        </div>

        <div class="col-7 row row-cols-2 g-3">
            {% for food in foods %}
            <div class="col">
                <div class="card border">
                    <div class="card-header p-3">
                        <img src="{{ food.image.url }}" class="w-100 rounded" style="height: 300px; object-fit: cover;">
                    </div>
                    <div class="card-body d-flex flex-column">
                        <a href="{% url 'food_detail' food.pk %}">
                            <h5>{{ food.name }}</h5>
                        </a>

                        <p class="card-text">{{ food.ingredients }}</p>

                        <div class="d-flex mt-3 align-items-center justify-content-between mt-auto">
                            <h5 class="mb-0">from {{ food.price }} sum</h5>

                            <div class=""><i class="fas fa-eye"></i> {{ food.views_count }}</div>
                        </div>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>
    </div>

</div>


<div class="modal fade" id="edit-food-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <form class="modal-content" method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Yangilash</h5>
                <button type="button" class="btn-close" data-mdb-ripple-init data-mdb-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {{ form.as_p }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-mdb-ripple-init data-mdb-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" data-mdb-ripple-init>Save changes</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

templates/home.html
{% extends 'base.html' %}





{% block action %}
{% if perms.project.add_food %}
<button class="btn btn-primary" data-mdb-ripple-init data-mdb-modal-init data-mdb-target="#add-food-modal">Add Food</button>
{% endif %}
{% endblock %}


{% block content %}

<div class="container">

    <div class="row row-cols-3 g-3">
        {% for food in foods %}
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <img src="{{ food.image.url }}" class="w-100 rounded" style="height: 350px; object-fit: cover;">
                </div>
                <div class="card-body d-flex flex-column">
                    <a href="{% url 'food_detail' food.pk %}">
                        <h5>{{ food.name }}</h5>
                    </a>

                    <p class="card-text">{{ food.ingredients }}</p>

                    <div class="d-flex mt-3 align-items-center justify-content-between mt-auto">
                        <h5 class="mb-0">from {{ food.price }} sum</h5>

                        <div class=""><i class="fas fa-eye"></i> {{ food.views_count }}</div>
                    </div>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>

    <div class="modal fade" id="add-food-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <form class="modal-content" method="POST" enctype="multipart/form-data">{% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add food</h5>
                    <button type="button" class="btn-close" data-mdb-ripple-init data-mdb-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {{ form.as_p }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-mdb-ripple-init data-mdb-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" data-mdb-ripple-init>Save changes</button>
                </div>
            </form>
        </div>
    </div>

</div>

{% endblock content %}